services:
  chrome:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_BROWSER=chrome
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev:chrome

  firefox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_BROWSER=firefox
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev:firefox